# Copyright 2023 Pluto TV

name: Attach release artifacts

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag of the release'
        required: true
        type: string

env:
  ARTIFACT_NAME: "artifact"

jobs:
  build_linux:
    name: Build artifact and upload
    runs-on: ubuntu-latest
    steps:
      - name: Install build tools
        run: |
          sudo apt update && sudo apt install -y \
              cmake

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
          submodules: recursive

      - name: Apply ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Generate build files
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"

          mkdir -p build/

          cmake \
            -DCMAKE_BUILD_TYPE="Release" \
            -DBUILD_SHARED_LIBS=1 \
            -S . \
            -B build/

      - name: Build
        run: cmake --build build/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: build/packager/libpackager.so

  update_release:
    needs: [build_linux]
    name: Update release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}

      # Debug
      - name: Display structure of downloaded files
        run: ls -la

      - name: Attach artifact
        id: attach_artifact
        uses: ncipollo/release-action@v1.13.0
        with:
          allowUpdates: true
          replacesArtifacts: true
          artifacts: libpackager.so
          token: ${{ secrets.GITHUB_TOKEN }}
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          tag: ${{ inputs.tag }}
          draft: false
